# Generated by Django 2.0.2 on 2018-03-28 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributeId', models.CharField(max_length=9)),
                ('attributeName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelId', models.CharField(max_length=10)),
                ('modelName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=8)),
                ('productName', models.CharField(max_length=200)),
                ('modelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningJump.Model')),
            ],
        ),
    ]
