# Generated by Django 2.0.2 on 2018-03-28 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningJump', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='attribute',
            old_name='attributeName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='modelName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='modelId',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='attributeId',
        ),
        migrations.RemoveField(
            model_name='model',
            name='modelId',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productId',
        ),
        migrations.AddField(
            model_name='product',
            name='avs',
            field=models.DateField(default='2099-12-31'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='model',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='value',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningJump.Attribute'),
        ),
        migrations.AddField(
            model_name='value',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningJump.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.ForeignKey(default='99', on_delete=django.db.models.deletion.CASCADE, to='learningJump.Department'),
        ),
    ]
